# Generated by Django 2.2.9 on 2020-01-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200107_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='tesst',
        ),
    ]
