# Generated by Django 2.2.9 on 2020-01-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200103_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="test",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
